config/routes.rb
Rails.application.routes.draw do
  mount API::Base => '/'
  mount Facebook::Messenger::Server, at: 'bot'
  mount Sidekiq::Web => "/sidekiq" # monitoring console

  get "registered_links/popularity/:id", to: "registered_links#popularity"

  devise_for :users, controllers: { sessions: "users/sessions", omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do

    authenticated :user do

      root "home#index", as: :authenticated_root
      get "base/contact_admin", to: "base#contact_admin", as: "contact_admin"

      scope :analytics do
        get "/",                    to: "analytics#index",               as: "analytics"
        get "/user_retention",      to: "analytics#user_retention",      as: "user_retention"
        get "/:id",                 to: "analytics#page_analytics",      as: "page_analytics"
        get "/:id/daily_new_users",     to: "analytics#daily_new_users",     as: "daily_new_users"
        get "/:id/daily_users_actions", to: "analytics#daily_users_actions", as: "daily_users_actions"
        get "/:id/user_activity",       to: "analytics#user_activity",       as: "user_activity"
        #get "/:id/sources",             to: "analytics#sources",             as: "sources"
      end

      get "fb_pages", to: "fb_pages#index", as: "fb_pages"
      post "fb_pages/register", to: "fb_pages#register", as: "register"

      resources :users
      resources :registered_links

      delete "registered_pages/:id", to: "bot_records#destroy", as: "destroy_registered_page"
      post "registered_pages/:id/subscriptions", to: "bot_records#subscribe", as: "registered_page_subscribe"
      delete "registered_pages/:id/subscriptions", to: "bot_records#unsubscribe", as: "registered_page_unsubscribe"
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/controllers/fb_pages_controller.rb
class FbPagesController < ApplicationController
  before_action :ensure_admin

  def index
    @registered_pages = BotRecord.all

    @user_fb_pages = current_user.fb_graph.get_connections("me", "accounts")
    @fb_pages = @user_fb_pages.select{ |p| p if !@registered_pages.map(&:page_id).include?(p.fetch("id")) }

  end

  def register
    bot_record = BotRecord.new(bot_record_params)
    if bot_record.save
      redirect_to fb_pages_path, alert: "ERROR!"
    else
      redirect_to fb_pages_path
    end
  end

  def subscribe
    Chatbot::Subscribe.call(bot_record: @bot_record, page_id: params[:page_id], page_access_token: params[:page_access_token])
    redirect_to authenticated_root_path, notice: "Subscribed to #{params[:page_name]}"
  end

  def unsubscribe
    #Facebook::Messenger::Subscriptions.unsubscribe(access_token: @bot.access_token)
    redirect_to authenticated_root, notice: "Disconnected to"
  end

  private
    def bot_record_params
      {
        name: params[:bot_record][:name],
        access_token: params[:bot_record][:access_token],
        page_id: params[:bot_record][:id],
      }
    end
end

app/views/fb_pages/index.html.erb
<% provide(:title, "My FB Pages") %>

<div class="subsection-body">
  <span class="head-title">Bot Publishing</span> <a href="https://www.facebook.com/pages/create/" target="_blank" >No page? Create here!</a>
  <div class="subsection-container">
    <p class="subsection-container-title">Your facebook Pages</p>
    <div class="fb-pages">
      <% @fb_pages.each do |fb_page| %>
      <div class="page-container">
        <img src="http://graph.facebook.com/v2.6/<%= fb_page.fetch("id") %>/picture" alt="<%= fb_page.fetch("name") %>"/>
        <%= fb_page.fetch("name") %>
        <%= link_to "Register!", register_path(bot_record: fb_page), method: :post %>
      </div>
      <% end %>
    </div>
  </div>

  <div class="subsection-container">
    <p class="subsection-container-title">Registered facebook page</p>
    <div class="fb-pages">
      <% @registered_pages.each do |registered_page| %>
      <div class="page-container">
        <img src="http://graph.facebook.com/v2.6/<%= registered_page.page_id %>/picture" alt="<%= registered_page.name %>"/>
        <%=registered_page.name%>

        <%= link_to "Remove", destroy_registered_page_path(registered_page), method: :delete, class: "warning", confirm: 'Are you sure?' %>
        <%= link_to "Subscribe", registered_page_subscribe_path(registered_page), method: :post, class: "success" %>
        <%= link_to "Analytics", page_analytics_path(registered_page) %>
      </div>
      <% end %>
    </div>
  </div>
</div>