config/routes.rb
Rails.application.routes.draw do
  mount API::Base => '/'
  mount Facebook::Messenger::Server, at: 'bot'
  mount Sidekiq::Web => "/sidekiq" # monitoring console

  get "registered_links/popularity/:id", to: "registered_links#popularity"

  devise_for :users, controllers: { sessions: "users/sessions", omniauth_callbacks: "users/omniauth_callbacks" }

  devise_scope :user do

    authenticated :user do

      root "home#index", as: :authenticated_root
      get "base/contact_admin", to: "base#contact_admin", as: "contact_admin"

      scope :analytics do
        get "/",                    to: "analytics#index",               as: "analytics"
        get "/user_retention",      to: "analytics#user_retention",      as: "user_retention"
        get "/:id",                 to: "analytics#page_analytics",      as: "page_analytics"
        get "/:id/daily_new_users",     to: "analytics#daily_new_users",     as: "daily_new_users"
        get "/:id/daily_users_actions", to: "analytics#daily_users_actions", as: "daily_users_actions"
        get "/:id/user_activity",       to: "analytics#user_activity",       as: "user_activity"
        #get "/:id/sources",             to: "analytics#sources",             as: "sources"
      end

      get "fb_pages", to: "fb_pages#index", as: "fb_pages"
      post "fb_pages/register", to: "fb_pages#register", as: "register"

      resources :users
      resources :registered_links

      delete "registered_pages/:id", to: "bot_records#destroy", as: "destroy_registered_page"
      post "registered_pages/:id/subscriptions", to: "bot_records#subscribe", as: "registered_page_subscribe"
      delete "registered_pages/:id/subscriptions", to: "bot_records#unsubscribe", as: "registered_page_unsubscribe"
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/registered_link.rb
# == Schema Information
#
# Table name: registered_links
#
#  content    :string
#  created_at :datetime         not null
#  id         :integer          not null, primary key
#  orig_url   :string           not null
#  title      :string
#  updated_at :datetime         not null
#

class RegisteredLink < ApplicationRecord
  validates :orig_url, :format => URI::regexp(%w(http https))
  validates :title, presence: true
  validates :title, uniqueness: true
end

app/controllers/registered_links_controller.rb
class RegisteredLinksController < ApplicationController
  before_action :ensure_super_admin, except: [:popularity]
  before_action :set_registered_link, only: [:destroy, :update, :edit]

  def index
    @registered_links = RegisteredLink.all.order(id: :asc)
  end

  def create
    @registered_link = RegisteredLink.new(registered_link_params)
    @registered_link.save
  end

  def edit

  end

  def update
    @registered_link.update(registered_link_params)
  end

  def destroy
    @registered_link.destroy
  end

  def popularity
    #routes > registered_links/popularity/:id?fb_obj_id=12312312321
    @registered_link = RegisteredLink.find_by(id: params[:id])
    if @registered_link
      # call on collagen page
      @fb_page = BotRecord.find(3)

      @fb_page.popular_urls.create(name: @registered_link.title, registered_link: @registered_link.orig_url, fb_obj_id: params[:fb_obj_id])
      redirect_to @registered_link.orig_url
    else
      # first data in RegisteredLink "FB WatsonsPH" => "https://www.messenger.com/t/WatsonsPH",
      redirect_to RegisteredLink.first.orig_url
    end

  end

  private
  def registered_link_params
    params.require(:registered_link).permit(:orig_url, :title)
  end

  def set_registered_link
    @registered_link = RegisteredLink.find(params[:id])
  end
end

app/helpers/registered_links_helper.rb
module RegisteredLinksHelper
end

app/views/registered_links/create.js.erb
<% if @registered_link.errors.present? %>
  $('.errors').show().html('<%=@registered_link.errors.full_messages%>').fadeOut(3000);
<% else %>
  var $html = '<tr id="registered_link_<%=@registered_link.id%>">'+
                '<td>'+
                  '<%=@registered_link.id%>'+
                '</td>'+
                '<td class="ellipsis">'+
                  '<%=@registered_link.orig_url%>'+
                '</td>'+
                '<td>'+
                  '<%=@registered_link.title%>'+
                '</td>'+
                '<td>'+
                  '<%= link_to "EDIT", edit_registered_link_path(@registered_link), remote: true, class: "warning" %>'+
                '</td>'+
              '</tr>';

  $('.appendable').append($html);
<% end %>

app/views/registered_links/destroy.js.erb
$('#registered_link_<%=@registered_link.id%>').remove();

app/views/registered_links/edit.js.erb
var $html = '<%= form_for @registered_link, remote: true do |f| %>'+
  '<td>'+
    'ID: <%=@registered_link.id%>'+
  '</td>'+
  '<td class="ellipsis">'+
    '<%= f.text_field :orig_url, placeholder: "URL" %>'+
  '</td>'+
  '<td>'+
    '<%= f.text_field :title, placeholder: "Title" %>'+
  '</td>'+
  '<td>'+
    '<%= f.submit "Save" %>'+
  '</td>'+
'<% end %>';
$('#registered_link_<%=@registered_link.id%>').children().hide();
$('#registered_link_<%=@registered_link.id%>').append($html);

app/views/registered_links/index.html.erb
<% provide(:title, "Chatbot Users") %>

<div class="subsection-body">
  <span class="head-title">Manage Registered URLs</span>
  <div class="subsection-container">
    <p class="subsection-container-title">Registered URLs</p>
    <div class="users-container">
      <table class="scrollable">
        <thead>
          <tr>
            <th>ID</th>
            <th>Original Url</th>
            <th>Title</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody class="appendable">
        <% @registered_links.each do |registered_link| %>
          <tr id="registered_link_<%=registered_link.id%>">
            <td>
              <%=registered_link.id%>
            </td>
            <td class="ellipsis">
              <%=registered_link.orig_url%>
            </td>
            <td>
              <%=registered_link.title%>
            </td>
            <td>
              <%= link_to "EDIT", edit_registered_link_path(registered_link), remote: true %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <div class="errors"></div>

      Register new URL with (https:// or http://)
      <div class="create-registered-link">
        <%= form_tag registered_links_path, method: :post, remote: true do %>
          <%= text_field_tag "registered_link[orig_url]", "", placeholder: "URL" %>
          <%= text_field_tag "registered_link[title]", "", placeholder: "URL Title" %>
          <button type="submit" name="button">Save</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/registered_links/update.js.erb
<% if @registered_link.errors.present? %>
  $('.errors').show().html('<%=@registered_link.errors.full_messages%>').fadeOut(3000);
<% else %>
  var $html = '<td>'+
                '<%=@registered_link.id%>'+
              '</td>'+
              '<td class="ellipsis">'+
                '<%=@registered_link.orig_url%>'+
              '</td>'+
              '<td>'+
                '<%=@registered_link.title%>'+
              '</td>'+
              '<td>'+
                '<%= link_to "EDIT", edit_registered_link_path(@registered_link), remote: true %>'+
              '</td>';

  $('#registered_link_<%=@registered_link.id%>').html($html);
<% end %>